# Site settings.
title:          âœ§ Music To Wake Up By
description:    "NASA's music to wakeup by turned into data"
url:            "https://nasawakeupcalls.github.io"

# Google Analytics.
google_analytics: UA-134142010-1

# Author
author:
  name:         Ross Spencer
  url:          "http://exponentialdecay.co.uk"
  email:        "all.along.the.watchtower2001+nasa@gmail.com"

# Build settings.
markdown:       kramdown
include:
  - _pages

# Assets.
sass:
  sass_dir:     _sass
  style:        compressed

# Gems.
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks.
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes.
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Social media.
github_link: nasawakeupcalls
twitter_username: beet_keeper
wordpress_link: http://exponentialdecay.co.uk/blog
